name: antigolpeia
description: "AntiGolpeia — Proteção inteligente contra golpes no WhatsApp, SMS e e-mail."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  http: ^1.6.0
  share_plus: ^12.0.2
  supabase_flutter: ^2.12.2
  receive_sharing_intent: ^1.8.1
  permission_handler: ^12.0.1
  notification_listener_service: ^0.3.5
  google_sign_in: ^7.2.0
  googleapis: ^16.0.0
  googleapis_auth: ^2.0.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  telephony: ^0.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.3
  workmanager: 0.9.0+3
  purchases_flutter: ^9.16.0
  purchases_ui_flutter: ^9.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0d0d0d"
  adaptive_icon_foreground: "images/logo.png"

flutter_native_splash:
  color: "#0d0d0d"
  image: images/logo.png
  android_12:
    color: "#0d0d0d"
    image: images/logo.png
    icon_background_color: "#0d0d0d"

flutter:
  uses-material-design: true
  assets:
    - .env
    - images/logo.png
